Added the track description of Middleware
alc-beijing/acasia2021 pull request #12
Opened 2021-03-19 15:06 UTC by terrymanu

2021-03-20 01:56 UTC, WillemJiang requested changes

2021-03-20 01:56 UTC, WillemJiang commented on content/tracks/Middleware.md
> +[Apache Kafka](https://kafka.apache.org/) and [Apache Pulsar](https://pulsar.apache.org/) are wonderful message middleware projects;
These two project are include in MessageQueue topic

2021-03-20 01:56 UTC, WillemJiang commented on content/tracks/Middleware.md
> +[Apache Tomcat](https://tomcat.apache.org/) is the most famous web server;
There is a webserver topic for Apache Tomcat.

2021-03-20 01:56 UTC, WillemJiang commented on content/tracks/Middleware.md
> +There are a variety of projects in ASF that provide middleware solutions. For example,
I think we can add Apache ServiceMix,  Apache Synapse ESB as an example.

2021-03-20 02:17 UTC, jiazhai commented on content/tracks/Middleware.md
> +They include web middleware, message middleware, database middleware, and someone to achieve specific requirements.
Is it Ok to remove the messaging middleware? Seems we have a track for Message, it may be confusing for speaker to choose.

2021-03-21 14:17 UTC, WillemJiang approved these changes

2021-03-21 14:17 UTC, merged